In [1]:
import numpy as np
#import gym
import sys
from PIL import Image
from matplotlib.pyplot import imshow
import matplotlib.pyplot as plt
import matplotlib


%matplotlib inline
#fig, ax = plt.subplots(figsize=(20, 10)) 
#fig, ax = plt.subplots(figsize=(18, 2))
#ax.imshow(random.rand(8, 90), interpolation='nearest')
#tight_layout()

#fig = matplotlib.pyplot.gcf()
#fig.set_size_inches(20,20)

sys.path.append('../src')
sys.path.append('../src/envs')
sys.path.append('../src/game_generator')
sys.path.append('../src/agents')
sys.path.append('../src/utils')

def showim(buffer):
    fig, ax = plt.subplots(figsize=(9, 9))
    #ax.imshow(random.rand(8, 90), interpolation='nearest')
    ax.imshow(buffer,interpolation='nearest',aspect='auto')

In [2]:
from four_in_a_row_env import FourInARowEnv

In [3]:
env = FourInARowEnv()

In [5]:
state = env.reset()
state

(array([[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]]), -1, -1)

In [6]:
env.step( 6)

check win
(-1, 4, 6)
check win
(1, 4, 2)


((array([[ 0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  1,  0,  0,  0, -1]]), 4, 6), 0, False, '')

In [7]:
env.step( 5)

check win
(-1, 4, 5)
check win
(1, 3, 5)


((array([[ 0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  1,  0],
         [ 0,  0,  1,  0,  0, -1, -1]]), 4, 5), 0, False, '')

In [8]:
env.step( 4)

check win
(-1, 4, 4)
check win
(1, 2, 5)


((array([[ 0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  1,  0],
         [ 0,  0,  0,  0,  0,  1,  0],
         [ 0,  0,  1,  0, -1, -1, -1]]), 4, 4), 0, False, '')

In [9]:
env.step( 3)

check win
(-1, 4, 3)
check win
(1, 4, 1)


((array([[ 0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  1,  0],
         [ 0,  0,  0,  0,  0,  1,  0],
         [ 0,  1,  1, -1, -1, -1, -1]]), 4, 3), 0, False, '')

In [24]:
env.step( 4)

((array([[ 0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  1,  0,  0,  0, -1],
         [ 0,  0,  1,  0,  0,  0,  1],
         [ 0,  0,  1,  0,  0,  0, -1],
         [ 0,  0,  1,  0, -1, -1, -1]]), 4, 4), -1, True, '')

In [10]:
env.step( 4)

((array([[ 0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0],
         [-1,  0,  0,  0,  0,  0, -1],
         [ 1,  1,  0,  0,  0,  1, -1],
         [ 1,  1,  1,  0, -1, -1, -1]]), 4, 4), 0, False, '')

In [11]:
env.step( 3)

((array([[ 0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0],
         [-1,  0,  0,  0,  0,  0, -1],
         [ 1,  1,  0,  0,  1,  1, -1],
         [ 1,  1,  1, -1, -1, -1, -1]]), 4, 3), 0, False, '')

In [19]:
np.random.choice( [ 1, 3 ,4 ,5])

3

In [22]:
a = np.random.randint( -1 , 1 , ( 6,7) ).astype(int)

In [18]:
env.board

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [-1,  0,  0,  0,  0,  0, -1],
       [ 1,  1,  0,  0,  1,  1, -1],
       [ 1,  1,  1, -1, -1, -1, -1]])

In [17]:
for i in range( 0 , env.in_row_count):
    a = np.sum( env.board[ 4, i:i+env.in_row_count]) == (4 * env.in_row_count )
    print(env.board[ 4, i:i+env.in_row_count])
    print (a)

env.board[4, :]

[1 1 0 0]
False
[1 0 0 1]
False
[0 0 1 1]
False
[ 0  1  1 -1]
False


array([ 1,  1,  0,  0,  1,  1, -1])

In [12]:
env.board

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [-1,  0,  0,  0,  0,  0, -1],
       [ 1,  1,  0,  0,  1,  1, -1],
       [ 1,  1,  1, -1, -1, -1, -1]])

In [36]:
np.where( a[0,:] == 0)


(array([0, 4, 6], dtype=int64),)

In [29]:
a

array([[ 0,  1, -1, -1,  0, -1,  0],
       [-1,  0,  0,  0, -1,  0, -1],
       [ 0, -1,  0, -1,  0, -1, -1],
       [ 0,  0,  0, -1,  0, -1,  0],
       [-1,  0, -1,  0, -1, -1,  0],
       [-1, -1,  0,  0, -1,  0,  0]])